# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
# https://taskfile.dev/
version: '3'


env:
  SOURCE_FOLDER: ./...
  CGO_ENABLED: 1

tasks:
  docker:build:
    desc: docker build
    cmds:
      - |
        docker build . --file Dockerfile --tag example:latest \
         --progress auto

  lint:
    desc: Use golangci-lint (.golangci.yml).
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run --fix
      - go run mvdan.cc/gofumpt@latest -w -l .
      - go run github.com/dkorunic/betteralign/cmd/betteralign@latest -test_files -generated_files -apply ./...

  unit_test:
    desc: Run test.
    cmds:
      - go test ./...

  race_test:
    desc: Run race test.
    cmds:
      - go test -race ./...

  download:
    desc: Run go mod tidy.
    cmds:
      - go mod tidy

  upgrade:
    desc: Check for latest direct dependencies.
    cmds:
      - go-mod-upgrade

  build:
    desc: Build sources
    cmds:
      - echo "OS:" {{OS}}, "ARCH:" {{ARCH}}
      - go build -v $SOURCE_FOLDER

  run:
    desc: main()
    cmds:
      - go run cmd/program.go

  all:
    desc: Run relevant tasks.
    cmds:
      - task: download
      - task: build
      - task: unit_test
      - task: race_test
      - task: lint

  default:
    desc: Run [all].
    cmds:
      - task: all
